name: build
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Run Tests
        run: |
          env PYTHONPATH=. python test/all.py
